fix new converity issues
dasJ/sd-zfs pull request #17
Opened 2016-12-29 15:20 UTC by ajs124

2016-12-29 16:35 UTC, dasJ requested changes

2016-12-29 16:35 UTC, dasJ commented on src/zfs-util.c
> -		close(fd);
Why remove this?

2016-12-29 16:40 UTC, ajs124 commented on src/zfs-util.c
> -		close(fd);
it's moved up, into the if since `fd` is uninitialized outside of it.

2017-01-17 09:30 UTC, dasJ approved these changes

2017-01-17 09:30 UTC, merged